name: mannar_web
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^4.0.2
  audioplayers: ^0.20.1
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.1
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  dio: ^4.0.5
  equatable: ^2.0.3
  file_picker: ^4.3.0
  firebase_analytics: ^9.0.4
  firebase_core: ^1.10.0
  firebase_messaging: ^11.2.6
  firebase_storage: ^10.2.4
  flutter:
    sdk: flutter
  # flutter_audio_recorder2: ^0.0.2
  flutter_bloc: ^8.0.1
  flutter_downloader: ^1.7.1
  flutter_local_notifications: ^9.0.2
  flutter_native_splash: ^1.3.1
  flutter_rating_bar: ^4.0.0
  flutter_switch: ^0.3.2
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.2.0
  gallery_saver: ^2.3.2
  google_fonts: ^2.1.0
  icon_badge: ^1.0.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  open_file: ^3.2.1
  path_provider: ^2.0.8
  permission_handler: ^8.1.1
  photo_view: ^0.13.0
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.7
  table_calendar: ^3.0.2
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # - assets/audios/
    - assets/images/mannar_logo.png
    - assets/images/logo_text.png
    - assets/images/camera_icon.png
    - assets/images/profile_icon.jpg
    - assets/images/filter.png
    - assets/images/S1.png
    - assets/images/Group12730.png
    - assets/images/Group13112.png
    - assets/images/Group13119.png
    - assets/images/Group13118.png
    - assets/images/video_call_off.png
    - assets/images/video_call_on.png
    - assets/images/background.jpg
